# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dts < Formula
  desc "This is a CLI application integrated with DBT (Data Build Tool) focused on establishing robust testing for data models."
  homepage "https://bigtimedata.io/"
  version "0.0.11"
  depends_on :macos

  on_intel do
    url "https://github.com/Big-Time-Data/homebrew-dts/releases/download/v0.0.11/dts_darwin_amd64.tar.gz"
    sha256 "38d667750210b4efd14c17976032b3d40683eda0fb07da7e708cf9fdebcbf07e"

    def install
      bin.install "dts"
    end
  end
  on_arm do
    url "https://github.com/Big-Time-Data/homebrew-dts/releases/download/v0.0.11/dts_darwin_arm64.tar.gz"
    sha256 "e0aad27dda61cc5402bd1f98cee9a4a797594b5b4050bb6434c737eeb7675a8a"

    def install
      bin.install "dts"
    end
  end
end
