# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dts < Formula
  desc "This is a CLI application integrated with DBT (Data Build Tool) focused on establishing robust testing for data models."
  homepage "https://bigtimedata.io/"
  version "0.0.3"
  depends_on :macos

  on_intel do
    url "https://github.com/Big-Time-Data/data-tools/releases/download/v0.0.3/dts_darwin_amd64.tar.gz"
    sha256 "2c8740471615a1d7bf9295301c8159b06346b9eaabc21218c86714975f3c1355"

    def install
      bin.install "dts"
    end
  end
  on_arm do
    url "https://github.com/Big-Time-Data/data-tools/releases/download/v0.0.3/dts_darwin_arm64.tar.gz"
    sha256 "b79d691433325b3889274433591d0d0387c90d292c5e3224939cb291d593397e"

    def install
      bin.install "dts"
    end
  end
end
