# This file was generated by GoReleaser. DO NOT EDIT.
cask "dts" do
  name "dts"
  desc "Data Tool Suite - Web IDE and MCP server for dbt projects"
  homepage "https://bigtimedata.io/"
  version "2.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dts"
  binary "dts_mcp"

  on_macos do
    url "https://github.com/Big-Time-Data/homebrew-dts/releases/download/v#{version}/dts_darwin_all.tar.gz"
    sha256 "d3a26873eefc87ac730f9fb30e47e62762e7d7e7ca5b1835a44b4070dbfc55f4"
  end

  caveats do
    "DTS has been installed with:"
    "  - dts: Web IDE server"
    "  - dts_mcp: MCP server for Claude Code"
    ""
    "To start the web IDE:"
    "  dts"
    ""
    "Claude Plugin Setup:"
    "  claude plugin marketplace add Big-Time-Data/homebrew-dts"
    "  claude plugin install dts@dts-marketplace"
    ""
    "For the legacy CLI (v0.18.x):"
    "  brew install Big-Time-Data/dts/dts-legacy"
  end

  # No zap stanza required
end
